### ISSUE TITLE
Scheduled tasks decrement `repeats` infinitely

### ISSUE THREAD

**Issue by tcdent** [django-q2/django-q2#101]
https://github.com/django-q2/django-q2/blob/master/django_q/scheduler.py#L76C32-L76C32

This makes sense for scheduled tasks which will expire and stay at zero, but are there any consequences (or benefits) to decrementing this value indefinitely on permanent tasks?

**Comment by GDay** [comment]
Only benefit I see is that you can see how many times something has run, but I don't think that adds a lot of value (and it's unclear anyway).

The integerfield (https://docs.djangoproject.com/en/4.2/ref/models/fields/#integerfield) has a limit of `-2147483648`, while extremely rare, someone could be hitting that (as it won't stop with decrementing) and then django-q(2) would likely stop functioning.

So it's definitely worth fixing. Thanks for reporting this!

**Comment by Bonekit** [comment]
Hello,

When can we expect a fix for this bug?
