### ISSUE TITLE
[Suggestion] Add "Migration" section to documentation (DjangoQ -> DjangoQ2)

### ISSUE THREAD

**Issue by EdmundoDelGusto** [django-q2/django-q2#104]
Hi, I'm so glad this project exists! Discovered it recently and thought about migrating from django-q to django-q2. 

Would be nice if there is a "How to migrate from DjangoQ" section in the documentation. Even if the answer is "just remove django-q and install django-q2".  This would give me more confidence when migrating.

**Comment by GDay** [comment]
Good idea. Will do!
