### ISSUE TITLE
How can I sponsor this project?

### ISSUE THREAD

**Issue by MadcowD** [django-q2/django-q2#105]

**Comment by GDay** [comment]
Appreciate the willingness to sponsor this project! Thanks!

Maybe I will set up an open collective dedicated to this package at some point, but for now the only way to sponsor me is through my company. I work as a freelancer and on my own product. Sponsoring me would allow me to free up some extra time to spend on django-q2. 

If you would be open to that, then you can send me an email: hello@chiefonboarding.com
