### ISSUE TITLE
Scheduled Chain

### ISSUE THREAD

**Issue by zN3utr4l** [django-q2/django-q2#111]
In Celery it is possible, from one task, to lunch others, with task_func_name.apply_async(), I used this trick to chain the tasks to each other, launching it in the backgroud and continuing with the execution of the remaining code of the first task. Is it possible to do this in django-q? I saw https://django-q2.readthedocs.io/en/master/chain.html#chains, but it's not quite the same as described above, I can't do it in a Scheduled way or am I wrong?

I'm using windows, while for celery I used linux, so I don't even know if what I described is replicable.
Reading here: https://django-q2.readthedocs.io/en/master/install.html#windows, I think not right?

**Comment by GDay** [comment]
I think you are trying to do something like this?
https://github.com/chiefonboarding/ChiefOnboarding/blob/2d7b30ffb5cbc0edcb3bab03e28d08c198cd6b0c/back/users/tasks.py#L16-L36

That function is ran every hour through the scheduler. Once it finds a match, it sends off a new Django-q2 task that actually does the sending of the email (so it won't get stuck on that if it takes a longer time).

**Comment by zN3utr4l** [comment]
Yes Perfect.
another question, why the Schedule table has no contraint? I assumed that name is unique or a group of fields is unique, for example:

constraints = [
            models.UniqueConstraint(
                fields=['name', 'func', 'args', 'kwargs'], name='unique_schedule')
        ]

**Comment by GDay** [comment]
> Why the Schedule table has no contraint?

I think this has never been implemented because the original Django-q is very old (probably created before constraints through Django where a thing). I haven't gotten around to implementing one (a PR is welcome!).

> I can not set the retry to None, if I want to avoid the behavior that a task even if not finished after x seconds is re-executed as I do?

Yeah, I don't think that's possible. `Retry` is a global setting and cannot be overwritten by a task/schedule at the moment.
