### ISSUE TITLE
How to get group tasks results sorted ?

### ISSUE THREAD

**Issue by KrustyHack** [django-q2/django-q2#122]
Ay,

Sorry if my question is stupid, but I'm trying to launch several tasks :

```
def helloworld(message):
    # Randomly sleep
    time.sleep(random.randint(1, 10))

    print(f"Hello World : {message}")
    return f"Hello World : {message}"


delete_group("helloworld")

for i in range(100):
    async_task(helloworld, i, group="helloworld")

# wait until the group has 100 results
result = result_group("helloworld", count=100)
for r in result:
    print(r)
```

But I receive the results unsorted (as mentioned in the doc). How can I do to wait all tasks and get the result sorted ?

I was thinking about having the function called to return the result and the iterator and then sort the results list but I wanted to know if there is a better solution for that. :)

Sorry if it's not the good place to ask this, feel free to delete my issue.

Thanks for your help !

EDIT : here is the solution I did, I don't know if it's the best but at least it works.

```
def test_task(message, tid):
    # Randomly sleep
    time.sleep(random.randint(1, 10))
    return {"response": f"{message}:{tid}", "id": tid}

delete_group("test_task")

for i in range(10):
    async_task(test_task, "helloworld", i, group="test_task")

# wait until the group has 4 results
results = result_group("test_task", count=10)
sorted_results = sorted(results, key=lambda k: k['id'])
for r in sorted_results:
    print(r)
```

Will give :

```
{'response': 'helloworld:0', 'id': 0}
{'response': 'helloworld:1', 'id': 1}
{'response': 'helloworld:2', 'id': 2}
{'response': 'helloworld:3', 'id': 3}
{'response': 'helloworld:4', 'id': 4}
{'response': 'helloworld:5', 'id': 5}
{'response': 'helloworld:6', 'id': 6}
{'response': 'helloworld:7', 'id': 7}
{'response': 'helloworld:8', 'id': 8}
{'response': 'helloworld:9', 'id': 9}
```

**Comment by GDay** [comment]
> here is the solution I did, I don't know if it's the best but at least it works.

Yup, I would agree that that is the best approach here!

**Comment by KrustyHack** [comment]
Ay,

Ok thanks ! Then I think we can close this issue.
