### ISSUE TITLE
Setting orm to different value than default fails

### ISSUE THREAD

**Issue by skontar** [django-q2/django-q2#125]
I have set my databases to be:
```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / ".." / "data" / "db.sqlite3",
    },
    "scheduler": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / ".." / "data" / "scheduler.sqlite3",
    }
}
```
And q_cluster settings to:
```
Q_CLUSTER = {
    "name": "Notifications",
    "orm": "scheduler",
    "timeout": 60,
    "catch_up": False,
    "workers": 1,
}
```

I then run:
```
python ../src/manage.py migrate
python ../src/manage.py migrate --database=scheduler
python ../src/manage.py set_schedules
python ../src/manage.py qcluster
```

Where `set_schedules` does bunch of `Schedule.objects.update_or_create`

It seems that the `default` database is used anyway and I get `django.db.utils.ProgrammingError: Cannot operate on a closed database.` later.

Am I doing something wrong setting it up?

**Comment by msabatier** [comment]
The "orm" setting is only used to control where the queue table is stored when you are using the OrmQ broker.

If you also want to use a specific database for schedules and results you will need to setup a django database router for that.

**Comment by msabatier** [comment]
Something along those lines should work with a db connection called 'django_q_db'. 
Can be changed to 'scheduler' if you want.

````python
class DjangoQRouter:
    def db_for_read(self, _model, **_hints):
        if _model._meta.app_label == 'django_q':
            return 'django_q_db'
        return None

    def db_for_write(self, _model, **_hints):
        if _model._meta.app_label == 'django_q':
            return 'django_q_db'
        return None

    def allow_relation(self, _obj1, _obj2, **_hints):
        return None

    def allow_migrate(self, db, _app_label, _model_name=None, **_hints):
        if _app_label == 'django_q':
            return db == 'django_q_db'
        return None

**Comment by skontar** [comment]
Thanks. I did setup a db router and it seems to work as expected.
