### ISSUE TITLE
Best way to ensure "Quality of Service" for some tasks

### ISSUE THREAD

**Issue by vasco-wa** [django-q2/django-q2#132]
I have a big Django monolith, using Django-Q to perform some async tasks and lots of scheduled tasks. Some with with high cadence (every 15 minutes or so). I have some critical paths that should run at all time.   
So I want to make sure that there are always some workers left to run these tasks. Or at lease have a way to specify "X workers for one domain, Y workers for another".

From what I understood from your documentation, Django-Q doesn't have this kind of granularity with workers. But it's possible to do something of the sort with multiple `qcluster` processes.

Here's what I did:
1. Started a `qcluster` process, without a `name`. (I'll call this CLUSTER_1)
2. Started a `qcluster` process, with `name == MY_DOMAIN`. (I'll call this CLUSTER_2)
3. In my running Django application, I spawned a task with something like `async_task(my_func)`
5. => The task was correctly picked up and executed by CLUSTER_1.
6. Still in the same Django application, I spawned a task with something like `async_task(my_func, q_options={'cluster': 'MY_DOMAIN'})`.
7. => As expected, the task was picked up by CLUSTER_2. But it crashed due to mismatching signatures: `django.core.signing.BadSignature: Signature "qftSu0Vqbqn4f656oTiHlKZGvIWJ6UOLtVokHJnxvJs" does not match`

So my issue has sort of two approaches:
1. How can I go around the signature validation? (or ensure that it works for all I described earlier). Or,
2. (going back to the beginning of my message) How can I have some worker dedicated exclusively just for some tasks.

**Comment by GDay** [comment]
> How can I go around the signature validation? (or ensure that it works for all I described earlier).
 
Yes, you will have to set the same name, connect to the same broker and use the same secret key. (ref: https://django-q2.readthedocs.io/en/master/cluster.html#multiple-clusters)

You are very close to what you want to achieve. Django-q2 offers multiple queues and that's what you need for this. (ref: https://django-q2.readthedocs.io/en/master/cluster.html#multiple-queues). You will have to set an environment variable with the cluster name. This cluster name is not the same as the `name` prop in the settings! These are two different things.

You will also have to define the `ALT_CLUSTERS` in the settings. 

You should then pass the cluster name to any of the async_task or schedule functions and you should be good to go!

**Comment by vasco-wa** [comment]
Thank you!

That worked perfectly. 😄
