### ISSUE TITLE
Switch base62 decoding for Django 4?

### ISSUE THREAD

**Issue by niekbosch** [django-q2/django-q2#133]
Hi,

Thanks for your effort on this project. We just swapped Django-Q for Django-Q2 and it this works very well. So, thanks for your effort!

As a small note, I am fond of keeping my code warning free. Using Django 4(.2.6), I get a deprecation warning:

> RemovedInDjango50Warning: The django.utils.baseconv module is deprecated.

Looking into the code, I see you start using a different version for base64 conversion as of Django 5. So, practically, there won't be a problem. However, it might be nice to lower this version check and start using the new module already from Django version 4 and up? It will at least save us a deprecation warning.

https://github.com/django-q2/django-q2/blob/503127233fa7e7e6fae5901a45270071f2051a6d/django_q/core_signing.py#L11

Thanks for your effort in advance!

**Comment by GDay** [comment]
I have just rewritten it to just try to get it from the new location and then fail with an import error to the old location. It's in master, but might take a bit of time before I release a new version.

**Comment by niekbosch** [comment]
Nice solution. Again, thanks for your work!
