### ISSUE TITLE
Unexpected "sqlite3.OperationalError: database is locked"

### ISSUE THREAD

**Issue by skontar** [django-q2/django-q2#144]
Hello. I think I configured django-q2 to completely avoid writing collisions, so SQLite database as a backend can be easily used. However, I still get this error occasionally.

I have the following setting to avoid collisions between scheduler and main application (and database router). I also set timeout to 60 seconds, so SQLite should wait for a minute if the settings are propagated correctly.
```python
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / ".." / "data" / "db.sqlite3",
        "OPTIONS": {
            "timeout": 60,
        },
        "CONN_MAX_AGE": 0,
    },
    "scheduler": {  # Avoid database write collisions between main application and scheduler
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / ".." / "data" / "scheduler.sqlite3",
        "OPTIONS": {
            "timeout": 60, 
        },
        "CONN_MAX_AGE": 0,
    },
}
```

I also use only one worker, so if I understand correctly, only one process should write to the SQLite database.
```python
Q_CLUSTER = {
    "name": "Notifications",
    "orm": "scheduler",  # Avoid writing collisions on SQLite main model database
    "timeout": 60,
    "catch_up": False,
    "workers": 1,  # Avoid writing collisions on SQLite
    "pool": 5,  # Avoid high CPU usage
    "save_limit": 1000,  # Store more successful results
    "ack_failures": True,  # Do not retry failed tasks by default
}
```

Am I missing something? I do not need high performance, so I thought I should be able to use SQLite if correct precautions are made.

**Comment by GDay** [comment]
> "pool": 5,

I think that should be `poll`, not `pool`. 

The issue you are having is probably related to this issue: https://github.com/django-q2/django-q2/discussions/141
The `guard_cycle` saves the status of the cluster every 0.5 seconds, which is why you are likely getting the "locked" error. 

I haven't had time yet to rewrite that part, but it's on my list. You can change the `guard_cycle` and the error will likely happen much less.

**Comment by skontar** [comment]
Thank you @GDay, I will try these settings. And that typo is pure :man_facepalming:. 
However, I thought setting timeout to 60 would make any database write wait up to 60 seconds until it fails? It seems like that it ignored?

**Comment by GDay** [comment]
No, it doesn't wait with writing to the db, it only checks how long a task is processing and kills it if it exceeds the timeout. See: https://django-q2.readthedocs.io/en/master/configure.html#timeout

**Comment by skontar** [comment]
I meant the other timeout on the Django database setting.

**Comment by skontar** [comment]
For the record: It did not help. It is really better to use dedicated database.
