### ISSUE TITLE
Tasks repeating every minute when scheduled to 15mins or more.

### ISSUE THREAD

**Issue by mast3rbow** [django-q2/django-q2#149]
Hi, I've got an interesting bug, not too sure what would be causing this, but I am getting repeating tasks as below.
![image](https://github.com/django-q2/django-q2/assets/19358000/c0270161-9e34-40bd-af31-a9570a01f966)

Each of these tasks are configured at different schedules (smallest one is 15minutes), to the largest one being daily. 

Leveraging Redis Cache as the broker, below is the config of how settings are configured.
  
  ack_failure = True
  catch_up = False
  compress = False
  max_attempts = 1
  name = random_name
  queue_limit = 100
  retry = 600
  save_limit = 100
  timeout = 60
  worker = 2

I'm trying to work out where to start to isolate the issue.

**Comment by GDay** [comment]
The issue likely comes from the scheduler. This is really weird, never seen this before.

When I saw the screenshot I was immediately thinking about "catch_up". If there was an outage and the scheduler could have not ran, then it would catch up on the tasks and create something like that. However, you set that to False, so that's not possible.  

Is this constantly happening or has it stopped now?

**Comment by mast3rbow** [comment]
Constantly in both my QA and Prod environment. So it's interesting, where should I start to troubeshoot

Co-founder
Bryton Wishart
+61427594365
***@***.***



________________________________

**Comment by GDay** [comment]
Check what the schedules say: when is the next run. Does that seem right, or is it stuck at a value?

It sounds like it's not saving the next run value for you. This one:
https://github.com/django-q2/django-q2/blob/master/django_q/scheduler.py#L139

Why that would be, I have no clue. So if you could check what the next run is, then we at least know if the scheduler is functioning. 
Maybe you are overriding the `next_run` value yourself somewhere in your code?

**Comment by mast3rbow** [comment]
Yep, will have a look at soon in front of the PC, but first time I've ever seen this error too.

Thanks will start troubleshooting.

Co-founder
Bryton Wishart
+61427594365
***@***.***



________________________________

**Comment by mast3rbow** [comment]
I think I found the error, had the below build

                        if not s.schedule_type == s.ONCE:

when it should != s.Once. 

Thanks @GDay  for the support mate!

**Comment by GDay** [comment]
Anytime!

**Comment by mast3rbow** [comment]
@GDay, looking at function, looks to break if the next calculated run is behind the current localtime. This therefore stops schedules start again.

if Conf.CATCH_UP or next_run > localtime():
    break

I recommend maybe something below, which restart the timer counter and ensure the next_run isn't behind current time and avoid break.

if Conf.CATCH_UP or next_run > localtime():
      # Update next_run to be ahead of the localtime function
      next_run = localtime()
      next_run = s.calculate_next_run(next_run)
