### ISSUE TITLE
Repeating task even when next run shows in future.

### ISSUE THREAD

**Issue by mast3rbow** [django-q2/django-q2#150]
Hi, 

Back again, not sure what could cause this interesting, scheduling side seems to be correctly showing the next run, and that is working. However the task appears to run in chunks of 5 or 6 times every hour.
 
Example of the Alert spam (where Django Q2 has run the same alert multiple times)
![image](https://github.com/django-q2/django-q2/assets/19358000/a75e7518-7dbd-4646-ad7b-31f19892fc5d)

The Scheduled task in the admin
![image](https://github.com/django-q2/django-q2/assets/19358000/d1582895-b4b2-4db7-823f-cb4c0f5f03c2)

Below is the code of the task that is triggered (could it be something in my logic?)
```
def maintenance_tracker_processor():
    """
    Creates an alert, when maintenance checklist isn't completed per scheduled
    time
    """
    timezone.activate(TenantInformation.get_timezone())
    current_month = timezone.now().month
    mainteance_checklist = MaintenanceCheckList.objects.filter(
        created__month=current_month
    )

    if not mainteance_checklist.exists():
        new_alert = Alert.objects.filter(alert_type=4, status=1)
        if not new_alert.exists():
            alert_generator(obj=None, alert_type=4, alert_var=None)

```

Below cluster config.
```
# Q Cluster events
Q_CLUSTER = {
    "worker": 2
    "timeout": 60
    "max_attempts":1
    "retry": 120
    "ack_failure": False
    "compress": True
    "catch_up": False
    "redis": some-redis-link
```

**Comment by GDay** [comment]
Code looks fine. Are you sure you are not triggering the task from somewhere else as well? The hour difference in the tasks that get triggered don't really make sense either. Are these also showing up on the "successful tasks" part of the django-q admin part?

**Comment by mast3rbow** [comment]
I haven't been able to catch it in the successful tasks queue, because I have a couple other tasks which run quite often (15mins), and on-demand (update search attributes of items in the DB.) 

I have had to implement this in a multi-tenant apporach
https://github.com/mast3rbow/django_tenants_q2/tree/main/django_tenants_q

I will check to make sure no other call is calling it the function too.

**Comment by msabatier** [comment]
> I haven't been able to catch it in the successful tasks queue, because I have a couple other tasks which run quite often (15mins), and on-demand (update search attributes of items in the DB.)

To improve this you can use the _save_limit_per_ configuration setting to avoid having the same task fill the whole success history. See  [here](https://django-q2.readthedocs.io/en/master/configure.html#save-limit-per) for details.

**Comment by mast3rbow** [comment]
> > I haven't been able to catch it in the successful tasks queue, because I have a couple other tasks which run quite often (15mins), and on-demand (update search attributes of items in the DB.)
> 
> To improve this you can use the _save_limit_per_ configuration setting to avoid having the same task fill the whole success history. See [here](https://django-q2.readthedocs.io/en/master/configure.html#save-limit-per) for details.

Yep, will make this change and see if i can catch this interesting error.

**Comment by GDay** [comment]
This has been resolved in private (over email), it turned out to be something unrelated to django-q2.
