### ISSUE TITLE
Chain processing tasks in default cluster instead of alt_cluster

### ISSUE THREAD

**Issue by ruuushhh** [django-q2/django-q2#153]
I am passing `q_options` in `chain.append()` as a param to process task in alt cluster, but it processes task in default cluster.

`chain.append('task_to_be_processed', 1, q_options={'cluster': 'test_cluster'})`

I did check the underlying code and found out that we are using `async_chain` and `async_tasks` where `async_task` function works fine with `q_options`.

The problem is in file `django_q/tasks.py` on line number 492:
 `kwargs["broker"] = broker or get_broker()`
 
 Here `get_broker` function is assigning  cluster as default cluster.
 
 @GDay

**Comment by ruuushhh** [comment]
@GDay Can you please help me with this?

**Comment by GDay** [comment]
I am very busy at the moment, but I will try to look at this tomorrow. Thanks for letting me know.

**Comment by GDay** [comment]
@ruuushhh Sorry for the delay on this. You are right.

Could you elaborate a bit more on the usecase for this? I have taken a look and the current implementation of the chain is pretty much set to one broker. Meaning, if you have a chain of multiple tasks that need to run on multiple different clusters, then that's not going to work. It would require quite a few changes to make that work and I am not sure if that would ever be an actual usecase.

Instead, I have now created a PR that will allow you to set the broker (with the cluster key) on the chain. All tasks will then be completed on that cluster. Would that be enough for you or do you need to run different tasks (within one chain) on multiple clusters?

**Comment by ruuushhh** [comment]
@GDay Thanks man for fixing this.

Also your understanding is right, I want to process all the tasks in one single cluster.

**Comment by GDay** [comment]
tomorrow

**Comment by GDay** [comment]
It's released now.
