### ISSUE TITLE
Connect to pydev debugger

### ISSUE THREAD

**Issue by oliverbienert** [django-q2/django-q2#155]
I use IntelliJ IDEA 2022.2.5 (Ultimate Edition) as my IDE and am trying to debug a background task by stopping at breakpoints etc.
However, when I start the cluster in debug mode, it exits with exit code 0 a couple of seconds later:

```
/home/oliver/.virtualenvs/portal/bin/python /home/oliver/.local/share/JetBrains/IntelliJIdea2022.2/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 33869 --file /home/oliver/projects/portal/manage.py qcluster
Connected to pydev debugger (build 222.4554.10)

Process finished with exit code 0
```
It does not matter if `DJANGO_DEBUG` is True or False.

Or should I ask this question the guys from Intellij/PyCharm?

I appreciate any insight in this matter.

Regards Oliver

**Comment by GDay** [comment]
Good questions, I don't use any of the IntelliJ products, but this is using pydev, which is a standalone package it seems.

For debugging/testing couldn't you just run django-q2 in sync mode? [Docs here](https://django-q2.readthedocs.io/en/master/configure.html#sync). In that case, it won't use the qcluster and also no other processes, so you could just debug it like you would with other code. Would that work for you?

**Comment by oliverbienert** [comment]
Thank you, this works. My bad, I was almost there but did not realize that I don't have to start the cluster.

**Comment by Grayknife** [comment]
Mostly of the time i am using the `sync` flag as well, but sometimes I want to make a "real example" test within debug mode. 

There is a flag `gevent` you can set in the debug settings. With this flag set you should be able to use breakpoints in the cluster if you run it in debug mode.
I am using PyCharm Pro, but I would assume that its also available in IntelliJ:
<img width="491" alt="image" src="https://github.com/django-q2/django-q2/assets/75701163/1aeffecd-f645-4c8a-8f0b-82f502c60256">

After that, run the cluster in debug mode. For easyness I added a run configuration for the qcluster to the IDE:
<img width="425" alt="image" src="https://github.com/django-q2/django-q2/assets/75701163/f500c24a-0e6e-43d1-aef0-f09eed2deb8f">

**Comment by oliverbienert** [comment]
Great news! I didn't know about this configuration option. This works right out of the box with IntelliJ too. Thank you for sharing.
