### ISSUE TITLE
Consider adding index on `Task.success` field

### ISSUE THREAD

**Issue by Waszker** [django-q2/django-q2#160]
Looks like the monitor frequently executes the same command at the end of the task:
https://github.com/django-q2/django-q2/blob/1b638e5802c7cb045d71e5b9b75aae74690c0e7e/django_q/monitor.py#L111

This query can take a very long time if the number of task entries in the database (in failed state) is huge.

We've noticed that in one of our production systems where we had over 2M failed tasks, the aforementioned query was a bottleneck that prevented system from processing data in an efficient manner. It took over `1.5s` to execute.

After adding a partial index
```
CREATE INDEX django_q_success_manual ON django_q_task((1)) WHERE success;
```
the execution time went down to `1.3ms`.

I think a partial index would be the best here since the number of successful tasks is limited, contrary to failures.

**Comment by GDay** [comment]
Thanks a lot. I don't think we need a full index though, I have only put an index on the fields that we do lookups though. Doesn't really matter anyway, but it might save a few bytes in storage.

You can probably remove your index once you deploy the last version.
