### ISSUE TITLE
django-q2 and django-channels together

### ISSUE THREAD

**Issue by jankrnavek** [django-q2/django-q2#165]
Hi,
I am trying to run django-q2 and django-channels together but it fails.
Everything only works fine with qcluster in sync mode (sync=True)

My chain calls:
Regular django app -> async_task with hook  ->   hook that send channels message.

Any thoughts what can be wrong?

```
# asycn_task
def create_auto_snapshot(grid_uid: str):
   # do some work with django orm

    return new_grid_uid
```

```
# hook called from task
def hook_create_auto_snapshot(task):
    grid_uid = task.result

    # Send notification to all clients in the group
    channel_layer = get_channel_layer()
    channel_group_name = f"grid_group_{grid_uid}"

    async_to_sync(channel_layer.group_send)(
        channel_group_name,
        {"type": "send_notification"},
    )
```

**Comment by GDay** [comment]
> django-channels together but it fails

Does it give any error at all? What you have looks fine to me.

**Comment by jankrnavek** [comment]
I ran into this comment with the same type of issue.
https://stackoverflow.com/questions/77157325/sending-django-channels-message-from-inside-async-task

It`s possible that some passed context  is missing for the function hook_create_auto_snapshot  

It looks like I am gonna have to switch to Cellery. But I don't like...

**Comment by jankrnavek** [comment]
The problem solved. 
The reason was missing package **standard**  for uvicorn.
