### ISSUE TITLE
Task is never timed out

### ISSUE THREAD

**Issue by masb3** [django-q2/django-q2#173]
I use django orm with the following setting
```    
Q_CLUSTER = {
        'workers': 4,
        'timeout': 5,
        'retry': 10,
        'max_attempts': 1,
    }
```
Executing task `async_task('time.sleep', 22)` I expect it to fail after 5 seconds, instead `WARNING reincarnated worker Process-1:36 after timeout` and never ends.
Same if I increase 'retry' to 50:
```    
Q_CLUSTER = {
        'workers': 4,
        'timeout': 5,
        'retry': 50,
        'max_attempts': 1,
    }
```
How can the task be killed after `timeout` and `max_attempts`?

**Comment by GDay** [comment]
Indeed dup of #114 and will be fixed in https://github.com/django-q2/django-q2/pull/184
