### ISSUE TITLE
Timezone definition in the scheduled task

### ISSUE THREAD

**Issue by ThomasDeudon** [django-q2/django-q2#190]
Hello,

First, thank you for the project, very helpful. 

I am trying to have scheduled task in a CRON setup to have a timezone attached. 

Example : "30 8 * * 1" could be with GMT or with NYK timezone and would be understood (and not looking only at the cluster timezone), is there a way to do this properly ? 

The only solution I am seeing is to have a queue per timezone and having this forced to a specific queue (But this seems sub optimal to say the least), any suggestions ?

**Comment by GDay** [comment]
Hmm.. Another solution would be to create 4 schedules. One for each timezone and then another one for each for daylight savings. Then in the task check which one needs to run based on the time.

Still not ideal, but might be doable for now as a workaround.

**Comment by ThomasDeudon** [comment]
Sorry my question was not clear so my understanding of your answer is not certain. 

I want to be able to say for example 2 schedules : 

1. "30 8 * * 1" with "GMT" so that it runs at 8:30 GMT on the monday 
2. "30 9 * * 1" with "NYC" so that it runs at 9:30 NYC on the monday

This is doable with only one queue initialized with a timezone of SGT for example ?

**Comment by GDay** [comment]
> This is doable with only one queue initialized with a timezone of SGT for example ?

Yes, but there are two caveats:

I think SGT doesn't have daylight savings, that's good.

There is daylight savings for GMT and NYC and the days they switch will be different from each other.

So what you would need to do is create 4 schedules:
- cron for GMT not using daylight savings (change the `8` value to match the hour in GMT compared to SGT time)
- cron for GMT using daylight savings (change the `8` value to match the hour in GMT compared to SGT time)
- cron for NYC not using daylight savings (change the `9` value to match the hour in NYC compared to SGT time)
- cron for NYC using daylight savings (change the `9` value to match the hour in NYC compared to SGT time)

Then when running the function, check what the current hour is in the timezone and only continue if it is the hour you want it to run.

It's a bit of workaround, but it should work fine.

Does that make sense?

**Comment by ThomasDeudon** [comment]
thanks for the answer.
Unfortunately the different timezone I want to offer have different times for DST and it would be difficult to keep track.
I think I will go through the multiple clusters with different timezone solution

**Comment by ThomasDeudon** [comment]
Update: my solution does not work. 

The schedule is created by the Django app (using TIME_ZONE in settings) and this date seems to be in naive time so besides comparing their timezone with the default one, the clusters cannot understand properly the schedule. (And it seems that it is simply ignoring the time_zone provided to them anyway).

Seems there is no other choice than pre-processing the CRON even though it's not the cleanest thing to do from a data perspective..

**Comment by ThomasDeudon** [comment]
Sorry for last message, if a force timezone in the settings depending on the cluster name, this actually works !

**Comment by ThomasDeudon** [comment]
The above worked.
