### ISSUE TITLE
Get more info on tasks

### ISSUE THREAD

**Issue by ThomasDeudon** [django-q2/django-q2#204]
Hello,

Is there a way to know the cluster / machine used by a task ?

I guess I could add it in the result for the successful ones but how would it be done for failures / queued ones (maybe the most important ones) 

Thanks,

**Comment by GDay** [comment]
Couldn't get this through the `Q_CLUSTER_NAME` environment variable?

**Comment by ThomasDeudon** [comment]
Yes, actually the cluster name can be found. For the machine I guess I'll have to save it as a variable (as few clusters can have the same name across different machines)
