### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by d3corator** [django-q2/django-q2#211]
Following the instructions in `readme.rst` the docker compose command fails while building the container from Dockerfile.dev with the following error:

`
12.14   psutil could not be installed from sources because gcc is not installed. Try running:
12.14     sudo apt-get install gcc python3-dev
12.14   error: command 'gcc' failed: No such file or directory
`

**Comment by GDay** [comment]
Very strange, I just started fresh and I didn't get that error. I think gcc should be installed by default on the docker image we use.
