### ISSUE TITLE
UNIX `top` like interface to see running tasks

### ISSUE THREAD

**Issue by careyminaieva** [django-q2/django-q2#214]
Hello, nice to use your software to support a large application with a lots of tasks running every day, you did really great job at making its easy to install and use, guys!
Although, I have a small question like, maybe I missed something in documentation to this project.
Is there a chance for me to see in Django Admin interface a sign that indicates that certain tasks are running currently (not only scheduled via Admin, but those created dynamically from a HTTP request demand)? Or if Django Admin interface is limited (I understand that, its really quite limited thing to work with), is there a command line utility that not only shows running uhm... workers or clusters, but also shows tasks that are running? Similar to what `ps` or `top` might feature.
Thanks you guys for spending time on reading this, hope to see some response, and anyways, have a great day and once again, thanks for your product, for some folks out there its really vital!

**Comment by msabatier** [comment]
Hello,

You just need to install the optional setproctitle dependency (see https://django-q2.readthedocs.io/en/master/install.html#optional). Then the process title will be updated with the name of the currently running task.

You can then just do `ps -ef | grep qcluster` or just use top and you will get something like : 
```
django    338849       1  0 Sep05 ?        00:00:02 qcluster MainProcess minnesota-december-louisiana-bulldog
django    338872  338849  0 Sep05 ?        00:10:25 qcluster MainProcess minnesota-december-louisiana-bulldog
django    338877  338872  0 Sep05 ?        00:00:42 qcluster Process-78263c873d114f38b30683c4dc7f397d monitor
django    338878  338872  0 Sep05 ?        00:00:27 qcluster Process-1bb06c9a750a493f98687fc5b0f3c24b pusher
django    346893  338872  3 08:59 ?        00:08:21 qcluster Process-3744e22f8d4941cf85e3dd90199b60c1 idle
django    347113  338872  0 10:04 ?        00:00:41 qcluster Process-c77446bd2f6e497393c25e77048d746c processing nitrogen-beryllium-oven-tango 'function' [group]
django    347413  338872  0 12:47 ?        00:00:03 qcluster Process-db671459e93e4cd3a64c18290ea9fa72 idle
django    347440  338872  0 13:04 ?        00:00:01 qcluster Process-1bfd9e900da24674a71bfebe21a40682 idle
```
Here _nitrogen-beryllium-oven-tango_ is the task_id and you will also get the name of the function that is run and the name of the task group if it has been defined.

**Comment by careyminaieva** [comment]
Hello, @msabatier , I'm really grateful for your time and help :)

It will significantly improve application monitoring and maintenance! I'm now closing this issue as solved one :)
