### ISSUE TITLE
Django-q multiple queues

### ISSUE THREAD

**Issue by woshiyanghai** [django-q2/django-q2#218]
How do I configure multiple queues in django-q? Can I configure the priority of asynchronous tasks?How I configure

**Comment by GDay** [comment]
Please read the docs:
https://django-q2.readthedocs.io/en/master/configure.html#alt-clusters
https://django-q2.readthedocs.io/en/master/configure.html#configuration
https://django-q2.readthedocs.io/en/master/cluster.html#multiple-queues

> Can I configure the priority of asynchronous tasks?

No, this is not possible.
