### ISSUE TITLE
Key Error: ack_id when running in django unit tests on 1.7.2

### ISSUE THREAD

**Issue by dustinblanchard** [django-q2/django-q2#219]
Our unit tests are failing after upgrading to 1.7.2. Each one throws the following error:

`KeyError: 'ack_id'
Could not save task result
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/django_q/monitor.py", line 149, in save_task
    broker.acknowledge(task["ack_id"])
                       ~~~~^^^^^^^^^^`

**Comment by GDay** [comment]
Strange. I don't see anything in the changes that should have triggered this. 
What broker are you using?

**Comment by dustinblanchard** [comment]
We're using the redis broker.

**Comment by blockisec** [comment]
same issue on my side without using redis. We are using Django DB

**Comment by GDay** [comment]
This should be fixed in the latest version.
