### ISSUE TITLE
Help Debugging Qcluster in AWS EB, coz is killing me 🧔🏻‍♂️

### ISSUE THREAD

**Issue by ditorelo** [django-q2/django-q2#221]
Team, pulling literal hairs out of my beard here with this one. 
I have THE MOST vanilla qcluster setup on my project. 

```
Q_CLUSTER = {
    'retry': 60,
    'timeout': 30,
    'workers': 10,
    'orm': 'default',
    'compress': True,
    'cpu_affinity': 1,    
    'label': 'Django Q',    
}
```

Works perfectly locally, no issues whatsoever, my tasks run when they're scheduled, it's beautiful and elegant and I've been loving developing using it. 

When I put it on a AWS EB deploy, it completely kills the machine. All requests stop working, I have to SSH into a terminal that is absolutely crawling and run `kill` on workers or python3 processes (more below) and after waiting for a long time for the machine to respond they die and everything comes back to normal - Django admin and my application come to life and work expected. If I kick qcluster up again, death comes back. And, THERE IS NO TASKS SCHEDULED YET, so I'm stumped.

I tried running it using my project Procfile. I stopped that.
I now have been ssh-ing into the machine and running the manage.py command manually to see if I could do some easier debugging, but not change. 

I googled the whole of StackOverflow and Django forums, some people mentioned SSL connections in RDS, which I changed the settings but had no luck. I have Sentry in my project and it shows absolutely nothing related to this. 

Is there any debug I can do here to find the root clause? I looked at the qcluster command options and nothing seems to have a "step through" type of idea.
Anyone has run into anything like this in the past?

I tried using Celery and Dramatiq and really it didn't not match what DjangoQ can do. I don't want to change anything, so any help would be appreciated. 🫀

Many thanks.
Beardy.

**Comment by ditorelo** [comment]
Fair enough @gmseb !

- All browser requests to that server return a 504
- Bash commands into the machine become unresponsive (including Ctrl+C to kill `python manage.py qcluster`

Here's a screenshot I managed to take of the workers running under the manage.py command on the left side and the amount of memory each process is using in the machine on the right - 10 process using ~13% of the memory

![image](https://github.com/user-attachments/assets/f73cb956-5ed5-4110-bbcb-24a2e3a168b6)

**Comment by GDay** [comment]
Very strange, when I use your settings in Docker I get:

```
root@47b5927340fd:/app# ps aux --sort=%mem
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          21  0.4  0.0   4608  3708 pts/0    Ss   02:04   0:00 bash
root          27  0.0  0.0   8536  4240 pts/0    R+   02:04   0:00 ps aux --sort=%mem
root          12  0.0  0.0  53528 37132 ?        S    02:04   0:00 python manage.py qcluster
root          10  0.0  0.0  53520 37140 ?        S    02:04   0:00 python manage.py qcluster
root           9  0.0  0.0  53516 37180 ?        S    02:04   0:00 python manage.py qcluster
root          13  0.0  0.0  53532 37200 ?        S    02:04   0:00 python manage.py qcluster
root          14  0.0  0.0  53536 37200 ?        S    02:04   0:00 python manage.py qcluster
root          15  0.0  0.0  53540 37204 ?        S    02:04   0:00 python manage.py qcluster
root          16  0.0  0.0  53544 37208 ?        S    02:04   0:00 python manage.py qcluster
root          17  0.0  0.0  53548 37208 ?        S    02:04   0:00 python manage.py qcluster
root          11  0.0  0.0  53524 37216 ?        S    02:04   0:00 python manage.py qcluster
root          18  0.0  0.0  53552 37216 ?        S    02:04   0:00 python manage.py qcluster
root          19  0.0  0.0  53552 37216 ?        S    02:04   0:00 python manage.py qcluster
root          20  0.7  0.0  53552 39352 ?        S    02:04   0:00 python manage.py qcluster
root           8  0.2  0.0  53552 40552 ?        S    02:04   0:00 python manage.py qcluster
root           1  1.1  0.0  53272 45752 ?        Ss   02:04   0:00 python manage.py qcluster
```

Exactly what I would have expected.

What kind of configuration are you use? A VPS with RDS or with a local DB? What are the specs of that? How are you deploying it? Using docker or something else?

**Comment by GDay** [comment]
For testing, you could also try to set `guard_cycle` to `30` and `poll` to `20`.
That shouldn't affect the workers, but it will reduce the stress on the database, which might help a little.

**Comment by ditorelo** [comment]
Happy to close this - just tried in machine with higher specs and things are fine.
