### ISSUE TITLE
Documentation build artefacts

### ISSUE THREAD

**Issue by techdragon** [django-q2/django-q2#76]
The current documentation on readthedocs builds, but does not produce ZIP/PDF/ePub versions (which are handy for offline use)

Would be good to get this working.

**Comment by GDay** [comment]
Thanks for the suggestion. All formats are now supported. For example: https://django-q2.readthedocs.io/_/downloads/en/master/pdf/

**Comment by techdragon** [comment]
Thanks for the quick fix @GDay 👍
