### ISSUE TITLE
Is there a way to delay tasks?

### ISSUE THREAD

**Issue by NateV** [django-q2/django-q2#86]
I'd like to be able to set a delay on tasks. I would think one approach might be to create a Chain. The first task just `sleeps` for n seconds, and then my real job runs. But that seems like a waste of resources to have a worker processing that do-nothing job.

Is there a better approach?

And if there is a better place to discuss this, I will happily relocate my question. 

Thank you!

**Comment by NateV** [comment]
I'm not quite looking for a schedule, either - https://django-q2.readthedocs.io/en/master/schedules.html

I'd like the 'pusher' to only push tasks slowly. 

Basically, my jobs are calls to another resource that I don't want to call more often than once every 5 minutes. So can I limit the 'through rate' of jobs?

**Comment by GDay** [comment]
> The first task just sleeps for n seconds, and then my real job runs. But that seems like a waste of resources to have a worker processing that do-nothing job.

I am not entirely sure how your jobs run, but one way to get around that, could be to create a [schedule that runs once](https://django-q2.readthedocs.io/en/master/schedules.html#django_q.Schedule.ONCE) where you manually set the [next_run](https://django-q2.readthedocs.io/en/master/schedules.html#django_q.Schedule.next_run) value.

Could that work for you?

**Comment by NateV** [comment]
It might, with a modification. So I have requests for jobs coming in somewhat randomly distributed. Like there might be a request at time 0, and then another at time 0+1, and another at 0+3, and then 0+4.  (lets say these units are seconds)

Ultimately I want to space out all these jobs, so that I am running one job about every 10 seconds.

When some request for a job comes in, I don't know what the state of the queue is, so I don't know when I want to run this new job. Is the queue empty, and I can schedule it to run it immediately? Or does the queue have two other jobs, and I want to delay running it for 3*10 seconds?

So I'm thinking - what if I schedule the job to run at `now + random(0,30)`? Would this, on average, end up spacing out my jobs?

**Comment by NateV** [comment]
FYI - I wrote up this: https://replit.com/@JazzyBatman/RemoteEachPattern. It looks like this does work ... the average time-between events does increase with an increase to the number in `random(0,X)`. But X has to be really big ... I would love to understand mathematically what X needs to be, to achieve an average time-gap of Y. 

Anyway, this isn't an issue with django-q2, so I can close this. Thanks!
