### ISSUE TITLE
AttributeError: module 'django_q.models' has no attribute 'validate_kwarg'

### ISSUE THREAD

**Issue by omer-glazer** [django-q2/django-q2#98]
Hey, I have two dockers running two queues (one is default the other is for high-priority tasks).
Locally everything works as expected, but in production, with setup, in both dockers, I'm getting:

2023-05-18T08:48:34.470555779Z   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-05-18T08:48:34.470562179Z   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-05-18T08:48:34.470568480Z   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-05-18T08:48:34.470574880Z   File "/root/.local/lib/python3.9/site-packages/django_q/migrations/0016_schedule_intended_date_kwarg.py", line 7, in <module>
2023-05-18T08:48:34.470581481Z     class Migration(migrations.Migration):
2023-05-18T08:48:34.470587581Z   File "/root/.local/lib/python3.9/site-packages/django_q/migrations/0016_schedule_intended_date_kwarg.py", line 22, in Migration
2023-05-18T08:48:34.470593982Z     validators=[django_q.models.validate_kwarg],
2023-05-18T08:48:34.470600082Z AttributeError: module 'django_q.models' has no attribute 'validate_kwarg'

My settings look like this:
```
Q_CLUSTER = {
    'name': 'DJRedis_{0}_{1}'.format(os.environ.get('STAGE', 'Dev'), int(os.environ.get('LOCAL_Q', False))),
    'workers': 4,
    'timeout': 3000,
    'retry': 3600,
    'compress': True,
    'queue_limit': 500,
    'django_redis': 'default',
    'label': 'Django Q',
    'max_attempts': 2,
    'attempt_count': 1,
    'ALT_CLUSTERS': {
            'high': {
                'timeout': 180,
                'retry': 200,
                'max_attempts': 1,
            },
        }
}
```

If more information is needed to workaround this issue please let me know.
Thanks in advance :)

**Comment by GDay** [comment]
That's super strange, because the function that it tries to call exists:

https://github.com/django-q2/django-q2/blob/fb960104c389d6f25e6f3e744e471eed24588189/django_q/models.py#L159

I will try to reproduce when I have a bit of time

**Comment by omer-glazer** [comment]
![image](https://github.com/django-q2/django-q2/assets/130898333/d6b180b0-3095-4bf2-832b-4897e011931a)

@GDay Maybe this is something to do with the fact that there are two migrations with the same number initial?
In localhost, I had to apply make migrations with merge to resolve that issue (which creates migration step 18).
I know that the function exists I can see it in my venv, which makes it stranger.
Thanks!

**Comment by omer-glazer** [comment]
I should also mention that I upgraded from django-q, even though I uninstalled that and obviously I build the docker image with the new requirement.

**Comment by GDay** [comment]
I have just tried the following:
1. Start a completely fresh Django project in Docker
2. Installed django-q
3. Migrated database and created a `Schedule`
4. Removed django-q
5. Installed django-q2
6. Rebuild the entire docker image
7. Migrated the database again (only the migrations that django-q2 has on top of django-q were migrated, so the original tables were still there).

Ran into no issues at all. Everything worked flawless. Also, a few months ago, I have migrated one of my own applications from `django-q` to django-q2` and also that worked fine.

What's strange about your setup is the two migration files starting with `0015`. I don't know how you got those, but these are not in this repo: https://github.com/django-q2/django-q2/tree/master/django_q/migrations. `0015` is also not in the original `django-q` repo. 

Therefore, running `python manage.py makemigrations` results into "No changes detected" for me. 

When do you get that error? when installing the packages, starting the server or when running migrations?

**Comment by omer-glazer** [comment]
@GDay I really appreciate that. This error occurs with setup in production. When the image has been built successfully and the server loads it runs `makemigrations` and `migrate` to stay updated with local development, of course, then this is happen.
The difference in the migrations directory is honestly super weird.

**Comment by omer-glazer** [comment]
Thank you for your help, I was finally able to work out this issue.
I had to uninstall every package related to django_q including django_q[sentry]. delete some remaining files from somewhat reason, and then install django_q2 and django_q2[sentry] and now everything works!

**Comment by GDay** [comment]
Awesome. Good to hear that you figured it out! Thanks for letting me know.
